"""Soft delete for documents

Revision ID: 1b4b9fadc062
Revises: ce1f78cb67f5
Create Date: 2026-05-03 13:56:52.305691
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4b9fadc062'
down_revision: Union[str, None] = 'ce1f78cb67f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_deleted')
    # ### end Alembic commands ###
